/**
 * This file was automatically generated by the Mule Development Kit
 */
package org.mule.module.xero;

import org.mule.api.annotations.Connector;
import org.mule.api.annotations.Connect;
import org.mule.api.annotations.ValidateConnection;
import org.mule.api.annotations.ConnectionIdentifier;
import org.mule.api.annotations.Disconnect;
import org.mule.api.annotations.display.Placement;
import org.mule.api.annotations.param.Default;
import org.mule.api.annotations.param.Optional;
import org.mule.api.annotations.param.Payload;
import org.mule.api.ConnectionException;
import org.mule.api.annotations.Configurable;
import org.mule.api.annotations.Processor;
import org.springframework.beans.factory.annotation.Value;

/**
 * Cloud Connector
 *
 * @author MuleSoft, Inc.
 */

@Connector(name="xero", schemaVersion="1.0")
public class XeroConnector
{
	private static final String XERO_BASE_ENDPOINT = "https://api.xero.com/api.xro/2.0/";
	
	/**
     * Xero Account Consumer Key
     */
    @Configurable
    private String consumerKey;
    /**
     * Xero Account Consumer Secret
     */
    @Configurable
    private String consumerSecret;
    /**
     * Local path to Xero account private key file
     */
    @Configurable
    private String privateKeyPath;
    
    /**
     * Xero API Endpoint
     */
    @Configurable
    @Optional
    @Default(XERO_BASE_ENDPOINT) 
    private String xeroApiUrl;

    /**
     * The OAuth Consumer Key 
     * @param consumerKey Consumer Key
     */
    public void setConsumerKey(String consumerKey)
    {
        this.consumerKey = consumerKey;
    }
    
	/** 
	 * The OAuth Consumer Secret  
	 * @param consumerSecret Consumer Secret
	 * */
    public void setConsumerSecret(String consumerSecret)
    {
        this.consumerSecret = consumerSecret;
    }
    
    /** 
	 * The location of the private key file  
	 * @param privateKeyLoc Private Key File
	 * */
    public void setPrivateKeyPath(String privateKeyPath)
    {
        this.privateKeyPath = privateKeyPath;
    }
    
    /**
     * The Xero API URL - defaults to https://api.xero.com/api.xro/2.0/
     * @param xeroApiUrl Xero API URL
     */
    public void setXeroApiUrl(String xeroApiUrl)
    {
        this.xeroApiUrl = xeroApiUrl;
    }

    /**
     *{@sample.xml ../../../doc/Xero-connector.xml.sample xero:get-accounts-list}
     * 
     * getAccountsList
     * @param filterString filter string used to filter query results from Xero
     * @return - returns all accounts listed for the Xero domain.
     */    
    @Processor
    public String getAccountsList(@Optional String filterString)
    {
    	String response = null;
    	XeroConnectorClient xeroClient = new XeroConnectorClient(xeroApiUrl, consumerKey, consumerSecret, privateKeyPath);
    	try {
    		response = xeroClient.getAccountsList(filterString);
		} catch (XeroConnectorClientException e) {
			return e.getXeroException();
		} catch (XeroConnectorClientUnexpectedException e) {
			throw new RuntimeException(e);
		}  

        return response;
    }
    
    /**
     * {@sample.xml ../../../doc/Xero-connector.xml.sample xero:get-account}
     * 
     * getAccount
     * @param accountId a unique Xero account id
     * @return - returns details of an individual account
     */
    @Processor
    public String getAccount(@Optional @Default("#[message.payload]") String accountId)
    {
    	String response = null;
    	XeroConnectorClient xeroClient = new XeroConnectorClient(xeroApiUrl, consumerKey, consumerSecret, privateKeyPath);
    	try {
    		response = xeroClient.getAccount(accountId);
		} catch (XeroConnectorClientException e) {
			return e.getXeroException();
		} catch (XeroConnectorClientUnexpectedException e) {
			throw new RuntimeException(e);
		}  
        
    	return response;
    }
    
    /**
     * {@sample.xml ../../../doc/Xero-connector.xml.sample xero:get-invoices-list}
     * 
     * getInvoicesList
     * @param filterString filter string used to filter query results from Xero
     * @return - returns all invoices listed for the Xero domain.
     */    
    @Processor
    public String getInvoicesList(@Optional String filterString)
    {
    	String response = null;
    	XeroConnectorClient xeroClient = new XeroConnectorClient(xeroApiUrl, consumerKey, consumerSecret, privateKeyPath);
    	try {
    		response = xeroClient.getInvoicesList(filterString);
		} catch (XeroConnectorClientException e) {
			return e.getXeroException();
		} catch (XeroConnectorClientUnexpectedException e) {
			throw new RuntimeException(e);
		}  

        return response;
    }
    
    /**
     * {@sample.xml ../../../doc/Xero-connector.xml.sample xero:get-invoice}
     * 
     * getInvoice
     * @param invoiceId a unique Xero invoice id
     * @return - returns details of an individual invoice
     */
    @Processor
    public String getInvoice(@Optional @Default("#[message.payload]") String invoiceId)
    {
    	String response = null;
        XeroConnectorClient xeroClient = new XeroConnectorClient(xeroApiUrl, consumerKey, consumerSecret, privateKeyPath);
    	try {
    		response = xeroClient.getInvoice(invoiceId);
		} catch (XeroConnectorClientException e) {
			return e.getXeroException();
		} catch (XeroConnectorClientUnexpectedException e) {
			throw new RuntimeException(e);
		}  

        return response;
    }
    
    /**
     * {@sample.xml ../../../doc/Xero-connector.xml.sample xero:create}
     * 
     * create
     * @param objectType The type of object to be created in Xero
     * @param payload The content of the object to be created in Xero
     * @return - returns the status of the create request
     */
    @Processor
    public String create(XeroObjectTypes.XeroPostTypes objectType, 
    					 @Optional @Default("#[message.payload]") String payload)
    {
    	XeroConnectorClient xeroClient = new XeroConnectorClient(xeroApiUrl, consumerKey, consumerSecret, privateKeyPath);
    	String response = null;
		try {
			response = xeroClient.create(objectType, payload);
		} catch (XeroConnectorClientException e) {
			return e.getXeroException();
		} catch (XeroConnectorClientUnexpectedException e) {
			throw new RuntimeException(e);
		}    	
    	        
    	return response;
    }
    
    
    /*************************************************************************
     * Skeleton methods below required for Maven build - not used by connector
     ************************************************************************/
    
    /**
     * Connect
     *
     * @throws ConnectionException
     */
    @Connect
    public void connect()
        throws ConnectionException {
        /*
         * CODE FOR ESTABLISHING A CONNECTION GOES IN HERE
         */
    }

    /**
     * Disconnect
     */
    @Disconnect
    public void disconnect() {
        /*
         * CODE FOR CLOSING A CONNECTION GOES IN HERE
         */
    }
    
    @ValidateConnection
    public boolean isConnected() {
		return false;
    	
    }

    @ConnectionIdentifier
    public String getSessionId() {
		String sessionId = null;
    	
    	return sessionId; 
    
    }
}
